### ISSUE TITLE
自建服务不能同步大图片提示fileIsTooLarge

### ISSUE THREAD

**Issue by xygulu** [leanote/leanote#447]
自建的服务，发现部分笔记不能同步，检查发现如果图片比较大，可能超过1M，就没法同步笔记，同步时服务端命令行里提示
INFO  2016/10/22 10:54:24 Debug.go:10: fileIsTooLarge
INFO  2016/10/22 10:54:24 Debug.go:10: 580ac9cbe248cb71fe000004
请问是什么原因，如何解决
服务端版本 leanote-windows-amd64-v2.0 二进制版
客户端 leanote-desktop-windows-x64-v2.1

**Comment by mybuddy** [comment]
我遇到了类似的问题，我先在”后台管理“里调大了文件大小限制，发现没用。后来想，是不是nginx默认的文件上传大小限制，于是在nginx里设置了client_max_body_size 20M; 现在正常了。你也可以试下。

(for those who don't understand Chinese)
I encountered similar problem. First I configured the "Upload File Size Limit" in the leanote dashboard, but it didn't work. Then I thought it might because of the default nginx configuration, so I set "client_max_body_size 20M;" in nginx configuration and it worked. You can have a try.

**Comment by RMOTD** [comment]
如图，进admin设置
![2016-11-05 6 50 43](https://cloud.githubusercontent.com/assets/22410135/20029517/11ffb42a-a389-11e6-8cc6-809511ebec60.png)

**Comment by lealife** [comment]
@mybuddy 对, 可能是nginx的问题
