### ISSUE TITLE
Sequence and workflow diagram is not supported in blogs.

### ISSUE THREAD

**Issue by ZhouMoHan-work** [leanote/leanote#598]
They are correctly shown in notes,. But in blogs, those diagram only shows source code.

**Comment by mo-han** [comment]
Besides, "todo list" is displayed in source code such as `- [x] ...`.

**Comment by mo-han** [comment]
I found the reason, it's the `/public/libs/md2html/uml.js` from `leanote.com` which failed to load, thus cause the markdown code not parsed completely. Why is this javascript file not loaded? Because I enable SSL on my self-hosted Leanote service, but there is a file `leanote/public/libs/md2html/md2html.js` which try to load the `uml.js` from **http**://leanote.com rather than from **https**://leanote.com, and my browser refuse to goto a http link from a https site.

`leanote/public/libs/md2html/md2html.js` need to be modified, in line `loadJs('http://leanote.com/public/libs/md2html/uml.js', function() {`, where the `http` should be changed to `https`.
